global:
  name: vault
  enabled: true
  tlsDisable: true

server:
  enabled: true
  extraEnvironmentVars:
    VAULT_ADDR: "http://127.0.0.1:8200"

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3

  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true

      listener "tcp" {
        address     = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable = 1
      }

      storage "consul" {
        address = "consul-server.consul.svc.cluster.local:8500"
        path    = "vault/"
      }
      
      seal "awskms" {
        region     = "eu-central-1"
        kms_key_id = "8c8bfb2c-2212-4087-a279-8be6cd95d624"
      }

      api_addr = "http://vault-active.vault.svc.cluster.local:8200"
      cluster_addr = "http://vault-active.vault.svc.cluster.local:8201"
      disable_mlock = true

    dataStorage:
      enabled: true
      size: 10Gi
      storageClass: efs-sc
      accessMode: ReadWriteOnce

ui:
  enabled: true

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
