apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-consul-consul-consul-server-2
  namespace: consul
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
