apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: default
data:
  consul.hcl: |
    datacenter = "dc1"
    data_dir = "/consul/data"
    bind_addr = "0.0.0.0"
    client_addr = "0.0.0.0"
    retry_join = ["provider=k8s label_selector=\"app=consul,component=server\""]
    ui = true
    server = true
