apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: default
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:latest
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: config
          mountPath: /consul/config
        env:
        - name: CONSUL_LOCAL_CONFIG
          value: /consul/config/consul.hcl
      volumes:
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data
      - name: config
        configMap:
          name: consul-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - consul
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: volume-sc
      resources:
        requests:
          storage: 5Gi
