global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
  bootstrapExpect: 1
ui:
  enabled: true
client:
  enabled: true
connectInject:
  enabled: true
  webhookCert:
    secretName: consul-connect-inject-webhook-cert
