apiVersion: v1
kind: Service
metadata:
  name: consul-server
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 8500
    name: http
  - port: 8502
    name: https
  - port: 8301
    name: serf-lan
    protocol: TCP
  - port: 8301
    name: serf-lan
    protocol: UDP
  - port: 8302
    name: serf-wan
    protocol: TCP
  - port: 8302
    name: serf-wan
    protocol: UDP
  - port: 8300
    name: server
  - port: 8600
    name: dns
    protocol: TCP
  - port: 8600
    name: dns
    protocol: UDP
  selector:
    app: consul
    component: server
