apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8500
    protocol: TCP
  selector:
    app: consul
    component: server
