apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: default
spec:
  serviceName: "vault"
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        volumeMounts:
        - name: config
          mountPath: /vault/config
        command: ["vault", "server", "-config=/vault/config/vault.hcl"]
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard"
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
